// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: app_settings.sql

package repository

import (
	"context"
	"encoding/json"
)

const getAppSetting = `-- name: GetAppSetting :one
SELECT key, value, updated_at FROM app_settings WHERE key = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSetting, key)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at FROM app_settings ORDER BY key
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.Query(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppSetting = `-- name: UpsertAppSetting :one
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
RETURNING key, value, updated_at
`

func (q *Queries) UpsertAppSetting(ctx context.Context, key string, value json.RawMessage) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertAppSetting, key, value)
	var i AppSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppSetting = `-- name: DeleteAppSetting :exec
DELETE FROM app_settings WHERE key = $1
`

func (q *Queries) DeleteAppSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteAppSetting, key)
	return err
}
