// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: availability.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAvailabilityByEvent = `-- name: ListAvailabilityByEvent :many
SELECT ua.id, ua.event_id, ua.user_id, ua.start_time, ua.end_time, ua.status, ua.note, u.username, u.full_name AS user_full_name, u.display_name AS user_display_name
FROM user_availability ua
JOIN users u ON ua.user_id = u.id
WHERE ua.event_id = $1
ORDER BY ua.user_id, ua.start_time
`

type ListAvailabilityByEventRow struct {
	ID              uuid.UUID `json:"id"`
	EventID         uuid.UUID `json:"event_id"`
	UserID          uuid.UUID `json:"user_id"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	Status          string    `json:"status"`
	Note            *string   `json:"note"`
	Username        string    `json:"username"`
	UserFullName    string    `json:"user_full_name"`
	UserDisplayName *string   `json:"user_display_name"`
}

func (q *Queries) ListAvailabilityByEvent(ctx context.Context, eventID uuid.UUID) ([]ListAvailabilityByEventRow, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailabilityByEventRow{}
	for rows.Next() {
		var i ListAvailabilityByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Note,
			&i.Username,
			&i.UserFullName,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByEventAndUser = `-- name: ListAvailabilityByEventAndUser :many
SELECT id, event_id, user_id, start_time, end_time, status, note FROM user_availability WHERE event_id = $1 AND user_id = $2 ORDER BY start_time
`

func (q *Queries) ListAvailabilityByEventAndUser(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) ([]UserAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByEventAndUser, eventID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAvailability{}
	for rows.Next() {
		var i UserAvailability
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO user_availability (event_id, user_id, start_time, end_time, status, note) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, event_id, user_id, start_time, end_time, status, note
`

type CreateAvailabilityParams struct {
	EventID   uuid.UUID `json:"event_id"`
	UserID    uuid.UUID `json:"user_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Status    string    `json:"status"`
	Note      *string   `json:"note"`
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (UserAvailability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.EventID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Note,
	)
	var i UserAvailability
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Note,
	)
	return i, err
}

const deleteAvailabilityByEventAndUser = `-- name: DeleteAvailabilityByEventAndUser :exec
DELETE FROM user_availability WHERE event_id = $1 AND user_id = $2
`

func (q *Queries) DeleteAvailabilityByEventAndUser(ctx context.Context, eventID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilityByEventAndUser, eventID, userID)
	return err
}
