// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: coverage.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listCoverageRequirements = `-- name: ListCoverageRequirements :many
SELECT id, event_id, team_id, start_time, end_time, required_count FROM coverage_requirements WHERE event_id = $1 ORDER BY team_id, start_time
`

func (q *Queries) ListCoverageRequirements(ctx context.Context, eventID uuid.UUID) ([]CoverageRequirement, error) {
	rows, err := q.db.Query(ctx, listCoverageRequirements, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageRequirement{}
	for rows.Next() {
		var i CoverageRequirement
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.StartTime,
			&i.EndTime,
			&i.RequiredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverageRequirementsByTeam = `-- name: ListCoverageRequirementsByTeam :many
SELECT id, event_id, team_id, start_time, end_time, required_count FROM coverage_requirements WHERE event_id = $1 AND team_id = $2 ORDER BY start_time
`

func (q *Queries) ListCoverageRequirementsByTeam(ctx context.Context, eventID uuid.UUID, teamID uuid.UUID) ([]CoverageRequirement, error) {
	rows, err := q.db.Query(ctx, listCoverageRequirementsByTeam, eventID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoverageRequirement{}
	for rows.Next() {
		var i CoverageRequirement
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.StartTime,
			&i.EndTime,
			&i.RequiredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCoverageRequirement = `-- name: CreateCoverageRequirement :one
INSERT INTO coverage_requirements (event_id, team_id, start_time, end_time, required_count) VALUES ($1, $2, $3, $4, $5) RETURNING id, event_id, team_id, start_time, end_time, required_count
`

type CreateCoverageRequirementParams struct {
	EventID       uuid.UUID `json:"event_id"`
	TeamID        uuid.UUID `json:"team_id"`
	StartTime     time.Time `json:"start_time"`
	EndTime       time.Time `json:"end_time"`
	RequiredCount int32     `json:"required_count"`
}

func (q *Queries) CreateCoverageRequirement(ctx context.Context, arg CreateCoverageRequirementParams) (CoverageRequirement, error) {
	row := q.db.QueryRow(ctx, createCoverageRequirement,
		arg.EventID,
		arg.TeamID,
		arg.StartTime,
		arg.EndTime,
		arg.RequiredCount,
	)
	var i CoverageRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TeamID,
		&i.StartTime,
		&i.EndTime,
		&i.RequiredCount,
	)
	return i, err
}

const updateCoverageRequirement = `-- name: UpdateCoverageRequirement :one
UPDATE coverage_requirements
SET team_id = $2, start_time = $3, end_time = $4, required_count = $5
WHERE id = $1
RETURNING id, event_id, team_id, start_time, end_time, required_count
`

type UpdateCoverageRequirementParams struct {
	ID            uuid.UUID `json:"id"`
	TeamID        uuid.UUID `json:"team_id"`
	StartTime     time.Time `json:"start_time"`
	EndTime       time.Time `json:"end_time"`
	RequiredCount int32     `json:"required_count"`
}

func (q *Queries) UpdateCoverageRequirement(ctx context.Context, arg UpdateCoverageRequirementParams) (CoverageRequirement, error) {
	row := q.db.QueryRow(ctx, updateCoverageRequirement,
		arg.ID,
		arg.TeamID,
		arg.StartTime,
		arg.EndTime,
		arg.RequiredCount,
	)
	var i CoverageRequirement
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TeamID,
		&i.StartTime,
		&i.EndTime,
		&i.RequiredCount,
	)
	return i, err
}

const deleteCoverageRequirementByID = `-- name: DeleteCoverageRequirementByID :exec
DELETE FROM coverage_requirements WHERE id = $1
`

func (q *Queries) DeleteCoverageRequirementByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoverageRequirementByID, id)
	return err
}

const deleteCoverageRequirementsByEvent = `-- name: DeleteCoverageRequirementsByEvent :exec
DELETE FROM coverage_requirements WHERE event_id = $1
`

func (q *Queries) DeleteCoverageRequirementsByEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoverageRequirementsByEvent, eventID)
	return err
}

const deleteCoverageRequirementsByEventAndTeam = `-- name: DeleteCoverageRequirementsByEventAndTeam :exec
DELETE FROM coverage_requirements WHERE event_id = $1 AND team_id = $2
`

func (q *Queries) DeleteCoverageRequirementsByEventAndTeam(ctx context.Context, eventID uuid.UUID, teamID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoverageRequirementsByEventAndTeam, eventID, teamID)
	return err
}
