// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notifications.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldNotifications = `-- name: DeleteOldNotifications :execrows
DELETE FROM notifications WHERE created_at < $1 AND is_read = true
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldNotifications, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, event_id, title, body, trigger_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_id, title, body, trigger_type, is_read, created_at
`

type CreateNotificationParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	EventID     *uuid.UUID `json:"event_id"`
	Title       string     `json:"title"`
	Body        *string    `json:"body"`
	TriggerType string     `json:"trigger_type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.EventID,
		arg.Title,
		arg.Body,
		arg.TriggerType,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Title,
		&i.Body,
		&i.TriggerType,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, event_id, title, body, trigger_type, is_read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.Title,
			&i.Body,
			&i.TriggerType,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = true WHERE id = $1 AND user_id = $2
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id, userID)
	return err
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT user_id, trigger_type, channel, is_enabled FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.TriggerType,
			&i.Channel,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preferences (user_id, trigger_type, channel, is_enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, trigger_type, channel)
DO UPDATE SET is_enabled = EXCLUDED.is_enabled
`

type UpsertNotificationPreferenceParams struct {
	UserID      uuid.UUID `json:"user_id"`
	TriggerType string    `json:"trigger_type"`
	Channel     string    `json:"channel"`
	IsEnabled   bool      `json:"is_enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.TriggerType,
		arg.Channel,
		arg.IsEnabled,
	)
	return err
}
