// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oauth.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listOAuthProviders = `-- name: ListOAuthProviders :many
SELECT id, name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes, is_enabled, created_at FROM oauth_providers ORDER BY name
`

func (q *Queries) ListOAuthProviders(ctx context.Context) ([]OauthProvider, error) {
	rows, err := q.db.Query(ctx, listOAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthProvider{}
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientSecret,
			&i.AuthorizeUrl,
			&i.TokenUrl,
			&i.UserinfoUrl,
			&i.Scopes,
			&i.IsEnabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledOAuthProviders = `-- name: ListEnabledOAuthProviders :many
SELECT id, name FROM oauth_providers WHERE is_enabled = true ORDER BY name
`

type ListEnabledOAuthProvidersRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListEnabledOAuthProviders(ctx context.Context) ([]ListEnabledOAuthProvidersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledOAuthProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledOAuthProvidersRow{}
	for rows.Next() {
		var i ListEnabledOAuthProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthProviderByID = `-- name: GetOAuthProviderByID :one
SELECT id, name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes, is_enabled, created_at FROM oauth_providers WHERE id = $1
`

func (q *Queries) GetOAuthProviderByID(ctx context.Context, id uuid.UUID) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByID, id)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthProviderByName = `-- name: GetOAuthProviderByName :one
SELECT id, name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes, is_enabled, created_at FROM oauth_providers WHERE name = $1
`

func (q *Queries) GetOAuthProviderByName(ctx context.Context, name string) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByName, name)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthProvider = `-- name: CreateOAuthProvider :one
INSERT INTO oauth_providers (name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes, is_enabled, created_at
`

type CreateOAuthProviderParams struct {
	Name         string `json:"name"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	AuthorizeUrl string `json:"authorize_url"`
	TokenUrl     string `json:"token_url"`
	UserinfoUrl  string `json:"userinfo_url"`
	Scopes       string `json:"scopes"`
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, createOAuthProvider,
		arg.Name,
		arg.ClientID,
		arg.ClientSecret,
		arg.AuthorizeUrl,
		arg.TokenUrl,
		arg.UserinfoUrl,
		arg.Scopes,
	)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const updateOAuthProvider = `-- name: UpdateOAuthProvider :one
UPDATE oauth_providers SET
    name = COALESCE($2, name),
    client_id = COALESCE($3, client_id),
    client_secret = COALESCE($4, client_secret),
    authorize_url = COALESCE($5, authorize_url),
    token_url = COALESCE($6, token_url),
    userinfo_url = COALESCE($7, userinfo_url),
    scopes = COALESCE($8, scopes),
    is_enabled = COALESCE($9, is_enabled)
WHERE id = $1
RETURNING id, name, client_id, client_secret, authorize_url, token_url, userinfo_url, scopes, is_enabled, created_at
`

type UpdateOAuthProviderParams struct {
	ID           uuid.UUID `json:"id"`
	Name         *string   `json:"name"`
	ClientID     *string   `json:"client_id"`
	ClientSecret *string   `json:"client_secret"`
	AuthorizeUrl *string   `json:"authorize_url"`
	TokenUrl     *string   `json:"token_url"`
	UserinfoUrl  *string   `json:"userinfo_url"`
	Scopes       *string   `json:"scopes"`
	IsEnabled    *bool     `json:"is_enabled"`
}

func (q *Queries) UpdateOAuthProvider(ctx context.Context, arg UpdateOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, updateOAuthProvider,
		arg.ID,
		arg.Name,
		arg.ClientID,
		arg.ClientSecret,
		arg.AuthorizeUrl,
		arg.TokenUrl,
		arg.UserinfoUrl,
		arg.Scopes,
		arg.IsEnabled,
	)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecret,
		&i.AuthorizeUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthProvider = `-- name: DeleteOAuthProvider :exec
DELETE FROM oauth_providers WHERE id = $1
`

func (q *Queries) DeleteOAuthProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthProvider, id)
	return err
}

const getOAuthConnectionByExternalID = `-- name: GetOAuthConnectionByExternalID :one
SELECT id, user_id, provider_id, external_id, access_token, refresh_token, created_at FROM oauth_connections WHERE provider_id = $1 AND external_id = $2
`

func (q *Queries) GetOAuthConnectionByExternalID(ctx context.Context, providerID uuid.UUID, externalID string) (OauthConnection, error) {
	row := q.db.QueryRow(ctx, getOAuthConnectionByExternalID, providerID, externalID)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ExternalID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthConnectionsByUser = `-- name: ListOAuthConnectionsByUser :many
SELECT oc.id, oc.user_id, oc.provider_id, oc.external_id, oc.access_token, oc.refresh_token, oc.created_at, op.name AS provider_name
FROM oauth_connections oc
JOIN oauth_providers op ON oc.provider_id = op.id
WHERE oc.user_id = $1
`

type ListOAuthConnectionsByUserRow struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	ProviderID   uuid.UUID `json:"provider_id"`
	ExternalID   string    `json:"external_id"`
	AccessToken  *string   `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
	CreatedAt    time.Time `json:"created_at"`
	ProviderName string    `json:"provider_name"`
}

func (q *Queries) ListOAuthConnectionsByUser(ctx context.Context, userID uuid.UUID) ([]ListOAuthConnectionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOAuthConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOAuthConnectionsByUserRow{}
	for rows.Next() {
		var i ListOAuthConnectionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.ExternalID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.CreatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOAuthConnection = `-- name: CreateOAuthConnection :one
INSERT INTO oauth_connections (user_id, provider_id, external_id, access_token, refresh_token)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider_id, external_id, access_token, refresh_token, created_at
`

type CreateOAuthConnectionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ProviderID   uuid.UUID `json:"provider_id"`
	ExternalID   string    `json:"external_id"`
	AccessToken  *string   `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) CreateOAuthConnection(ctx context.Context, arg CreateOAuthConnectionParams) (OauthConnection, error) {
	row := q.db.QueryRow(ctx, createOAuthConnection,
		arg.UserID,
		arg.ProviderID,
		arg.ExternalID,
		arg.AccessToken,
		arg.RefreshToken,
	)
	var i OauthConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ExternalID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthConnection = `-- name: DeleteOAuthConnection :exec
DELETE FROM oauth_connections WHERE id = $1 AND user_id = $2
`

func (q *Queries) DeleteOAuthConnection(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthConnection, id, userID)
	return err
}
