// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: recovery_codes.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/google/uuid"
)

type CreateRecoveryCodesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCodes(ctx context.Context, arg []CreateRecoveryCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, pgx.Identifier{"recovery_codes"}, []string{"user_id", "code_hash"}, &iteratorForCreateRecoveryCodes{rows: arg})
}

type iteratorForCreateRecoveryCodes struct {
	rows []CreateRecoveryCodesParams
	skippedFirstNextCall bool
}

func (i *iteratorForCreateRecoveryCodes) Next() bool {
	if len(i.rows) == 0 {
		return false
	}
	if !i.skippedFirstNextCall {
		i.skippedFirstNextCall = true
		return true
	}
	i.rows = i.rows[1:]
	return len(i.rows) > 0
}

func (i *iteratorForCreateRecoveryCodes) Values() ([]interface{}, error) {
	return []interface{}{
		i.rows[0].UserID,
		i.rows[0].CodeHash,
	}, nil
}

func (i *iteratorForCreateRecoveryCodes) Err() error {
	return nil
}

const listRecoveryCodes = `-- name: ListRecoveryCodes :many
SELECT id, user_id, code_hash, used_at FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useRecoveryCode = `-- name: UseRecoveryCode :exec
UPDATE recovery_codes SET used_at = NOW() WHERE id = $1 AND user_id = $2 AND used_at IS NULL
`

func (q *Queries) UseRecoveryCode(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, useRecoveryCode, id, userID)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteUsedRecoveryCodes = `-- name: DeleteUsedRecoveryCodes :execrows
DELETE FROM recovery_codes WHERE used_at IS NOT NULL AND used_at < $1
`

func (q *Queries) DeleteUsedRecoveryCodes(ctx context.Context, usedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsedRecoveryCodes, usedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
