// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: shifts.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getShiftByID = `-- name: GetShiftByID :one
SELECT s.id, s.event_id, s.team_id, s.user_id, s.start_time, s.end_time, s.created_by, s.created_at, s.updated_at, t.abbreviation AS team_abbreviation, t.color AS team_color, t.name AS team_name,
       u.username, u.full_name AS user_full_name, u.display_name AS user_display_name
FROM shifts s
JOIN teams t ON s.team_id = t.id
JOIN users u ON s.user_id = u.id
WHERE s.id = $1
`

type GetShiftByIDRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	TeamID           uuid.UUID  `json:"team_id"`
	UserID           uuid.UUID  `json:"user_id"`
	StartTime        time.Time  `json:"start_time"`
	EndTime          time.Time  `json:"end_time"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	TeamAbbreviation string     `json:"team_abbreviation"`
	TeamColor        string     `json:"team_color"`
	TeamName         string     `json:"team_name"`
	Username         string     `json:"username"`
	UserFullName     string     `json:"user_full_name"`
	UserDisplayName  *string    `json:"user_display_name"`
}

func (q *Queries) GetShiftByID(ctx context.Context, id uuid.UUID) (GetShiftByIDRow, error) {
	row := q.db.QueryRow(ctx, getShiftByID, id)
	var i GetShiftByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TeamID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamAbbreviation,
		&i.TeamColor,
		&i.TeamName,
		&i.Username,
		&i.UserFullName,
		&i.UserDisplayName,
	)
	return i, err
}

const listShiftsByEvent = `-- name: ListShiftsByEvent :many
SELECT s.id, s.event_id, s.team_id, s.user_id, s.start_time, s.end_time, s.created_by, s.created_at, s.updated_at, t.abbreviation AS team_abbreviation, t.color AS team_color, t.name AS team_name,
       u.username, u.full_name AS user_full_name, u.display_name AS user_display_name, u.account_type
FROM shifts s
JOIN teams t ON s.team_id = t.id
JOIN users u ON s.user_id = u.id
WHERE s.event_id = $1
ORDER BY s.start_time, u.username
`

type ListShiftsByEventRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	TeamID           uuid.UUID  `json:"team_id"`
	UserID           uuid.UUID  `json:"user_id"`
	StartTime        time.Time  `json:"start_time"`
	EndTime          time.Time  `json:"end_time"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	TeamAbbreviation string     `json:"team_abbreviation"`
	TeamColor        string     `json:"team_color"`
	TeamName         string     `json:"team_name"`
	Username         string     `json:"username"`
	UserFullName     string     `json:"user_full_name"`
	UserDisplayName  *string    `json:"user_display_name"`
	AccountType      string     `json:"account_type"`
}

func (q *Queries) ListShiftsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListShiftsByEventRow, error) {
	rows, err := q.db.Query(ctx, listShiftsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftsByEventRow{}
	for rows.Next() {
		var i ListShiftsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamAbbreviation,
			&i.TeamColor,
			&i.TeamName,
			&i.Username,
			&i.UserFullName,
			&i.UserDisplayName,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftsByEventAndTeam = `-- name: ListShiftsByEventAndTeam :many
SELECT s.id, s.event_id, s.team_id, s.user_id, s.start_time, s.end_time, s.created_by, s.created_at, s.updated_at, t.abbreviation AS team_abbreviation, t.color AS team_color, t.name AS team_name,
       u.username, u.full_name AS user_full_name, u.display_name AS user_display_name
FROM shifts s
JOIN teams t ON s.team_id = t.id
JOIN users u ON s.user_id = u.id
WHERE s.event_id = $1 AND s.team_id = $2
ORDER BY s.start_time, u.username
`

type ListShiftsByEventAndTeamRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	TeamID           uuid.UUID  `json:"team_id"`
	UserID           uuid.UUID  `json:"user_id"`
	StartTime        time.Time  `json:"start_time"`
	EndTime          time.Time  `json:"end_time"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	TeamAbbreviation string     `json:"team_abbreviation"`
	TeamColor        string     `json:"team_color"`
	TeamName         string     `json:"team_name"`
	Username         string     `json:"username"`
	UserFullName     string     `json:"user_full_name"`
	UserDisplayName  *string    `json:"user_display_name"`
}

type ListShiftsByEventAndTeamParams struct {
	EventID uuid.UUID `json:"event_id"`
	TeamID  uuid.UUID `json:"team_id"`
}

func (q *Queries) ListShiftsByEventAndTeam(ctx context.Context, arg ListShiftsByEventAndTeamParams) ([]ListShiftsByEventAndTeamRow, error) {
	rows, err := q.db.Query(ctx, listShiftsByEventAndTeam, arg.EventID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftsByEventAndTeamRow{}
	for rows.Next() {
		var i ListShiftsByEventAndTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamAbbreviation,
			&i.TeamColor,
			&i.TeamName,
			&i.Username,
			&i.UserFullName,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftsByUser = `-- name: ListShiftsByUser :many
SELECT s.id, s.event_id, s.team_id, s.user_id, s.start_time, s.end_time, s.created_by, s.created_at, s.updated_at, t.abbreviation AS team_abbreviation, t.color AS team_color, t.name AS team_name,
       e.name AS event_name, e.slug AS event_slug
FROM shifts s
JOIN teams t ON s.team_id = t.id
JOIN events e ON s.event_id = e.id
WHERE s.user_id = $1
ORDER BY s.start_time
`

type ListShiftsByUserRow struct {
	ID               uuid.UUID  `json:"id"`
	EventID          uuid.UUID  `json:"event_id"`
	TeamID           uuid.UUID  `json:"team_id"`
	UserID           uuid.UUID  `json:"user_id"`
	StartTime        time.Time  `json:"start_time"`
	EndTime          time.Time  `json:"end_time"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	TeamAbbreviation string     `json:"team_abbreviation"`
	TeamColor        string     `json:"team_color"`
	TeamName         string     `json:"team_name"`
	EventName        string     `json:"event_name"`
	EventSlug        string     `json:"event_slug"`
}

func (q *Queries) ListShiftsByUser(ctx context.Context, userID uuid.UUID) ([]ListShiftsByUserRow, error) {
	rows, err := q.db.Query(ctx, listShiftsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftsByUserRow{}
	for rows.Next() {
		var i ListShiftsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamAbbreviation,
			&i.TeamColor,
			&i.TeamName,
			&i.EventName,
			&i.EventSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (event_id, team_id, user_id, start_time, end_time, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, event_id, team_id, user_id, start_time, end_time, created_by, created_at, updated_at
`

type CreateShiftParams struct {
	EventID   uuid.UUID  `json:"event_id"`
	TeamID    uuid.UUID  `json:"team_id"`
	UserID    uuid.UUID  `json:"user_id"`
	StartTime time.Time  `json:"start_time"`
	EndTime   time.Time  `json:"end_time"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift,
		arg.EventID,
		arg.TeamID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedBy,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TeamID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShift = `-- name: UpdateShift :one
UPDATE shifts SET
    team_id = COALESCE($2, team_id),
    start_time = COALESCE($3, start_time),
    end_time = COALESCE($4, end_time),
    updated_at = NOW()
WHERE id = $1
RETURNING id, event_id, team_id, user_id, start_time, end_time, created_by, created_at, updated_at
`

type UpdateShiftParams struct {
	ID        uuid.UUID  `json:"id"`
	TeamID    *uuid.UUID `json:"team_id"`
	StartTime *time.Time `json:"start_time"`
	EndTime   *time.Time `json:"end_time"`
}

func (q *Queries) UpdateShift(ctx context.Context, arg UpdateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, updateShift,
		arg.ID,
		arg.TeamID,
		arg.StartTime,
		arg.EndTime,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.TeamID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShift = `-- name: DeleteShift :exec
DELETE FROM shifts WHERE id = $1
`

func (q *Queries) DeleteShift(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShift, id)
	return err
}

const countShiftsInTimeRange = `-- name: CountShiftsInTimeRange :one
SELECT COUNT(*) FROM shifts
WHERE event_id = $1 AND team_id = $2
  AND start_time < $4 AND end_time > $3
`

type CountShiftsInTimeRangeParams struct {
	EventID   uuid.UUID `json:"event_id"`
	TeamID    uuid.UUID `json:"team_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CountShiftsInTimeRange(ctx context.Context, arg CountShiftsInTimeRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShiftsInTimeRange,
		arg.EventID,
		arg.TeamID,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOverlappingShifts = `-- name: GetOverlappingShifts :many
SELECT id, event_id, team_id, user_id, start_time, end_time, created_by, created_at, updated_at FROM shifts
WHERE user_id = $1 AND event_id = $2
  AND start_time < $4 AND end_time > $3
  AND ($5::uuid IS NULL OR id != $5)
`

type GetOverlappingShiftsParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	EventID   uuid.UUID  `json:"event_id"`
	StartTime time.Time  `json:"start_time"`
	EndTime   time.Time  `json:"end_time"`
	ExcludeID *uuid.UUID `json:"exclude_id"`
}

func (q *Queries) GetOverlappingShifts(ctx context.Context, arg GetOverlappingShiftsParams) ([]Shift, error) {
	rows, err := q.db.Query(ctx, getOverlappingShifts,
		arg.UserID,
		arg.EventID,
		arg.StartTime,
		arg.EndTime,
		arg.ExcludeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.TeamID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
