// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: smtp.sql

package repository

import (
	"context"
)

const getSMTPConfig = `-- name: GetSMTPConfig :one
SELECT id, host, port, username, password, from_address, from_name, use_tls, updated_at FROM smtp_config LIMIT 1
`

func (q *Queries) GetSMTPConfig(ctx context.Context) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, getSMTPConfig)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSMTPConfig = `-- name: UpsertSMTPConfig :one
INSERT INTO smtp_config (id, host, port, username, password, from_address, from_name, use_tls)
VALUES ('00000000-0000-0000-0000-000000000001'::uuid, $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    username = EXCLUDED.username,
    password = EXCLUDED.password,
    from_address = EXCLUDED.from_address,
    from_name = EXCLUDED.from_name,
    use_tls = EXCLUDED.use_tls,
    updated_at = NOW()
RETURNING id, host, port, username, password, from_address, from_name, use_tls, updated_at
`

type UpsertSMTPConfigParams struct {
	Host        string  `json:"host"`
	Port        int32   `json:"port"`
	Username    *string `json:"username"`
	Password    *string `json:"password"`
	FromAddress string  `json:"from_address"`
	FromName    *string `json:"from_name"`
	UseTls      bool    `json:"use_tls"`
}

func (q *Queries) UpsertSMTPConfig(ctx context.Context, arg UpsertSMTPConfigParams) (SmtpConfig, error) {
	row := q.db.QueryRow(ctx, upsertSMTPConfig,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.Password,
		arg.FromAddress,
		arg.FromName,
		arg.UseTls,
	)
	var i SmtpConfig
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.Password,
		&i.FromAddress,
		&i.FromName,
		&i.UseTls,
		&i.UpdatedAt,
	)
	return i, err
}
