// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: teams.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, abbreviation, color, sort_order, is_active, created_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Color,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamByAbbreviation = `-- name: GetTeamByAbbreviation :one
SELECT id, name, abbreviation, color, sort_order, is_active, created_at FROM teams WHERE abbreviation = $1
`

func (q *Queries) GetTeamByAbbreviation(ctx context.Context, abbreviation string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByAbbreviation, abbreviation)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Color,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, abbreviation, color, sort_order, is_active, created_at FROM teams ORDER BY sort_order, name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abbreviation,
			&i.Color,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTeams = `-- name: ListActiveTeams :many
SELECT id, name, abbreviation, color, sort_order, is_active, created_at FROM teams WHERE is_active = true ORDER BY sort_order, name
`

func (q *Queries) ListActiveTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listActiveTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Abbreviation,
			&i.Color,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, abbreviation, color, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, abbreviation, color, sort_order, is_active, created_at
`

type CreateTeamParams struct {
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	Color        string `json:"color"`
	SortOrder    int32  `json:"sort_order"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Abbreviation,
		arg.Color,
		arg.SortOrder,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Color,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET
    name = COALESCE($2, name),
    abbreviation = COALESCE($3, abbreviation),
    color = COALESCE($4, color),
    sort_order = COALESCE($5, sort_order),
    is_active = COALESCE($6, is_active)
WHERE id = $1
RETURNING id, name, abbreviation, color, sort_order, is_active, created_at
`

type UpdateTeamParams struct {
	ID           uuid.UUID `json:"id"`
	Name         *string   `json:"name"`
	Abbreviation *string   `json:"abbreviation"`
	Color        *string   `json:"color"`
	SortOrder    *int32    `json:"sort_order"`
	IsActive     *bool     `json:"is_active"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Abbreviation,
		arg.Color,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Abbreviation,
		&i.Color,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}
