// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Language,
		&i.AccountType,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.IsActive,
		&i.TimeFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Language,
		&i.AccountType,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.IsActive,
		&i.TimeFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Language,
		&i.AccountType,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.IsActive,
		&i.TimeFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at FROM users
WHERE ($1::varchar IS NULL OR role = $1)
  AND ($2::varchar IS NULL OR account_type = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	Role        *string `json:"role"`
	AccountType *string `json:"account_type"`
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Role, arg.AccountType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.DisplayName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Language,
			&i.AccountType,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.IsActive,
			&i.TimeFormat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, full_name, display_name, email, password_hash, role, language, account_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at
`

type CreateUserParams struct {
	Username     string  `json:"username"`
	FullName     string  `json:"full_name"`
	DisplayName  *string `json:"display_name"`
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Role         string  `json:"role"`
	Language     string  `json:"language"`
	AccountType  string  `json:"account_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Language,
		arg.AccountType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Language,
		&i.AccountType,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.IsActive,
		&i.TimeFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name = COALESCE($2, full_name),
    display_name = COALESCE($3, display_name),
    email = COALESCE($4, email),
    role = COALESCE($5, role),
    language = COALESCE($6, language),
    is_active = COALESCE($7, is_active),
    time_format = COALESCE($8, time_format),
    username = COALESCE($9, username),
    account_type = COALESCE($10, account_type),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID `json:"id"`
	FullName    *string   `json:"full_name"`
	DisplayName *string   `json:"display_name"`
	Email       *string   `json:"email"`
	Role        *string   `json:"role"`
	Language    *string   `json:"language"`
	IsActive    *bool     `json:"is_active"`
	TimeFormat  *string   `json:"time_format"`
	Username    *string   `json:"username"`
	AccountType *string   `json:"account_type"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.Language,
		arg.IsActive,
		arg.TimeFormat,
		arg.Username,
		arg.AccountType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Language,
		&i.AccountType,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.IsActive,
		&i.TimeFormat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateUserPassword(ctx context.Context, id uuid.UUID, passwordHash *string) error {
	_, err := q.db.Exec(ctx, updateUserPassword, id, passwordHash)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users SET totp_secret = $2, totp_enabled = $3, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetTOTPSecret(ctx context.Context, id uuid.UUID, totpSecret *string, totpEnabled bool) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, id, totpSecret, totpEnabled)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, full_name, display_name, email, password_hash, role, language, account_type, totp_secret, totp_enabled, is_active, time_format, created_at, updated_at FROM users
WHERE (username ILIKE '%' || $1 || '%' OR full_name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
ORDER BY username
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Query  string `json:"query"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.DisplayName,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Language,
			&i.AccountType,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.IsActive,
			&i.TimeFormat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
